FROM owncloudci/golang:1.16-amd64@sha256:17b9e5fd329a45439d26271b3c9c64580e82f2d75e5bdccf68477e3718e52298

COPY ./src /app/
WORKDIR /app
RUN go build -o wait-for .

FROM alpine:3.14@sha256:eb3e4e175ba6d212ba1d6e04fc0782916c08e1c9d7b45892e9796141b1d379ae

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="ownCloud CI wait-for"
LABEL org.opencontainers.image.url="https://hub.docker.com/r/owncloudci/wait-for"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/wait-for"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/wait-for"

COPY --from=0 /app/wait-for /usr/bin/wait-for
ENTRYPOINT [ "wait-for" ]
