FROM owncloudci/golang:1.20-amd64@sha256:457bbe98bef1a03314eafb971957b220d03be562243fa1e91bdcff8d49e59048

COPY ./src /app/
WORKDIR /app
RUN go build -o wait-for .

FROM alpine:3.18@sha256:82d1e9d7ed48a7523bdebc18cf6290bdb97b82302a8a9c27d4fe885949ea94d1

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="ownCloud CI wait-for"
LABEL org.opencontainers.image.url="https://hub.docker.com/r/owncloudci/wait-for"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/wait-for"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/wait-for"

COPY --from=0 /app/wait-for /usr/bin/wait-for
ENTRYPOINT [ "wait-for" ]
