FROM owncloudci/golang:1.17-arm64v8@sha256:d741d2f937085438bdb417ee530b765dfb4a7675e30a3a65a4ca45f546374510

COPY ./src /app/
WORKDIR /app
RUN go build -o wait-for .

FROM arm64v8/alpine:3.14@sha256:b4da1299e77c63f8706427cd39154e726a9b7646d29e2fc05d65b513373f9f5e

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="ownCloud CI wait-for"
LABEL org.opencontainers.image.url="https://hub.docker.com/r/owncloudci/wait-for"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/wait-for"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/wait-for"

COPY --from=0 /app/wait-for /usr/bin/wait-for
ENTRYPOINT [ "wait-for" ]
