FROM owncloudci/golang:1.20-amd64@sha256:5b05751dc9211fe55c717e6c3c7e39c4395133d07d984d314d0c451dbec262b3

COPY ./src /app/
WORKDIR /app
RUN go build -o wait-for .

FROM alpine:3.17@sha256:ff6bdca1701f3a8a67e328815ff2346b0e4067d32ec36b7992c1fdc001dc8517

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="ownCloud CI wait-for"
LABEL org.opencontainers.image.url="https://hub.docker.com/r/owncloudci/wait-for"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/wait-for"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/wait-for"

COPY --from=0 /app/wait-for /usr/bin/wait-for
ENTRYPOINT [ "wait-for" ]
