FROM owncloudci/golang:1.17-arm64v8@sha256:fea69a5de00fc97ef92bde61621ee258ef44927e7a9f7c909730f649f893ef23

COPY ./src /app/
WORKDIR /app
RUN go build -o wait-for .

FROM arm64v8/alpine:3.15@sha256:76467a0fb072205433a0596be103d4555357fced110dfc06ae74d16045ec5fc3

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="ownCloud CI wait-for"
LABEL org.opencontainers.image.url="https://hub.docker.com/r/owncloudci/wait-for"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/wait-for"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/wait-for"

COPY --from=0 /app/wait-for /usr/bin/wait-for
ENTRYPOINT [ "wait-for" ]
