FROM owncloudci/golang:1.17-arm32v7@sha256:c2438606a1ca8c27b80ef37de2519b18ef86ec21b8bc011a4d7d46b5d7be9143

COPY ./src /app/
WORKDIR /app
RUN go build -o wait-for .

FROM arm32v7/alpine:3.14@sha256:8595fe2e98735305ca7cbc68399d428d8bf1857daf13511db56a43e079ef960b

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="ownCloud CI wait-for"
LABEL org.opencontainers.image.url="https://hub.docker.com/r/owncloudci/wait-for"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/wait-for"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/wait-for"

COPY --from=0 /app/wait-for /usr/bin/wait-for
ENTRYPOINT [ "wait-for" ]
