FROM owncloudci/golang:1.16-arm32v7@sha256:7312bb6d2ff6b009cf7016f4ffae87eadb2efd342e1b8b9f495ffd10048e0786

COPY ./src /app/
WORKDIR /app
RUN go build -o wait-for .

FROM arm32v7/alpine:3.14@sha256:088557f18d845a348b4039a63c1266b09dfbe45619dc259f05742d902edd5f25

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="ownCloud CI wait-for"
LABEL org.opencontainers.image.url="https://hub.docker.com/r/owncloudci/wait-for"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/wait-for"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/wait-for"

COPY --from=0 /app/wait-for /usr/bin/wait-for
ENTRYPOINT [ "wait-for" ]
